config:
  behaviors:
    Player:
      trainer_type: ppo
      keep_checkpoints: 5
      max_steps: 80000000
      time_horizon: 64
      summary_freq: 20000

      hyperparameters:
        batch_size: 1024
        buffer_size: 10240
        learning_rate: 0.00005
        beta: 0.0003
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 8

      network_settings:
        hidden_units: 256
        num_layers: 3
        normalize: True
        memory:
          memory_size: 128
          sequence_length: 64

      reward_signals:
        extrinsic:
          gamma: 0.995
          strength: 1.0

        curiosity:
          strength: 0.13
          gamma: 0.99
          learning_rate: 0.0003

      self_play:
        window: 20
        play_against_latest_model_ratio: 0.5
        save_steps: 20000
        swap_steps: 10000
      team_change: 100000

  type: grid
  grid:
    stop: 10000
